### PR TITLE
Add db migration

### PR DESCRIPTION
**Pull request by bobholt**
This is a pre-requisite for adding a column to the `pull_request` table to fix the multi-comment situation (and for future database changes we want to perform on a live server).

~~Note this includes the standalone certbot versioning fix (https://github.com/w3c/wptdash/pull/18) as a different commit SHA. If that lands, this should be rebased.~~

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wptdash/19)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[migrations/env.py, line 1 at r1](https://reviewable.io:443/reviews/w3c/wptdash/19#-Ks37lSWiBClDFJuXrH5:-Ks37lSWiBClDFJuXrH6:bjjt4f0) ([raw file](https://github.com/w3c/wptdash/blob/c320ab1d5afec069c0f8568141782774e1d5153d/migrations/env.py#L1)):*
> ```Python
> from __future__ import with_statement
> ```

Surely this isn't needed here?

---

*[migrations/env.py, line 17 at r1](https://reviewable.io:443/reviews/w3c/wptdash/19#-Ks3B25iCDeAA9pukC40:-Ks3B25j-Oy5zUqR2dF1:b-xupm1s) ([raw file](https://github.com/w3c/wptdash/blob/c320ab1d5afec069c0f8568141782774e1d5153d/migrations/env.py#L17)):*
> ```Python
> 
> # add your model's MetaData object here
> # for 'autogenerate' support
> ```

Let's remove some of the commented out copy-paste (and maybe make the comments more relevant).

---

*[migrations/README, line 1 at r1](https://reviewable.io:443/reviews/w3c/wptdash/19#-Ks3BdE3mGiZtKqulXwu:-Ks3BdE3mGiZtKqulXwv:b1qc9kt) ([raw file](https://github.com/w3c/wptdash/blob/c320ab1d5afec069c0f8568141782774e1d5153d/migrations/README#L1)):*
> ```
> Generic single-database configuration.
> ```

This doesn't seem too helpful. Can we link to wherever this configuration came from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptdash/19)*

**Comment by bobholt** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[migrations/env.py, line 1 at r1](https://reviewable.io:443/reviews/w3c/wptdash/19#-Ks37lSWiBClDFJuXrH5:-Ks3ZWJl0vioBuur0Kds:bx5mu3b) ([raw file](https://github.com/w3c/wptdash/blob/c320ab1d5afec069c0f8568141782774e1d5153d/migrations/env.py#L1)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Surely this isn't needed here?
</blockquote></details>

This file was auto-generated by flask-migrate, so I didn't even look at it. I don't believe it will by any other automated scripts, so I'll clean it up.

---

*[migrations/README, line 1 at r1](https://reviewable.io:443/reviews/w3c/wptdash/19#-Ks3BdE3mGiZtKqulXwu:-Ks3_2MugdiHesfLfTuR:buxgr4f) ([raw file](https://github.com/w3c/wptdash/blob/c320ab1d5afec069c0f8568141782774e1d5153d/migrations/README#L1)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

This doesn't seem too helpful. Can we link to wherever this configuration came from?
</blockquote></details>

Another auto-generated file. I can remove it or add a note that all files in this directory are auto-generated by the migration script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptdash/19)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[migrations/README, line 1 at r1](https://reviewable.io:443/reviews/w3c/wptdash/19#-Ks3BdE3mGiZtKqulXwu:-Ks3dQyzpdRW97WlWF-H:b-b03j59) ([raw file](https://github.com/w3c/wptdash/blob/c320ab1d5afec069c0f8568141782774e1d5153d/migrations/README#L1)):*
<details><summary><i>Previously, bobholt (Bob Holt) wrote…</i></summary><blockquote>

Another auto-generated file. I can remove it or add a note that all files in this directory are auto-generated by the migration script.
</blockquote></details>

I assume the idea is that one cleans this up. But either way is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptdash/19)*

**Comment by bobholt** [comment]
Removed the README and cleaned up some comments. Remaining comments seem useful to me.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[migrations/env.py, line 17 at r1](https://reviewable.io:443/reviews/w3c/wptdash/19#-Ks3B25iCDeAA9pukC40:-Ks4TK3we0LFItM8kJjq:b-896fix) ([raw file](https://github.com/w3c/wptdash/blob/c320ab1d5afec069c0f8568141782774e1d5153d/migrations/env.py#L17)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Let's remove some of the commented out copy-paste (and maybe make the comments more relevant).
</blockquote></details>

Done.

---

*[migrations/README, line 1 at r1](https://reviewable.io:443/reviews/w3c/wptdash/19#-Ks3BdE3mGiZtKqulXwu:-Ks4TLHbgByB7DxE8M8U:b-896fix) ([raw file](https://github.com/w3c/wptdash/blob/c320ab1d5afec069c0f8568141782774e1d5153d/migrations/README#L1)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I assume the idea is that one cleans this up. But either way is fine.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptdash/19#-:-Ks4TO6vMWX4bNm7IMhn:b3jm30r)*

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptdash/19)*

**Review by jgraham — APPROVED** [review]

**Pull request merged**
