### PR TITLE
Add new deployer user

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Review by gsnedders — APPROVED** [review]

**Comment by gsnedders** [comment]
Wait I'm a deployer but I don't have write access to the repo? Interesting. cc/ @foolip

**Comment by foolip** [comment]
Probably a side effect of moving the repo. @jugglinmike is repo admin so I'll leave it to him how to organize permissions.

**Comment by jugglinmike** [comment]
I've designated all the folks who are listed as "deployers" to also be administrators of the GitHub repository.

As I try to wrangle roles/responsibilities across the new organization, I'm finding this level of granularity to be more of a burden than a help. Privilege isolation is a best practice, though; maybe I'm too trusting.

**Comment by jugglinmike** [comment]
Thanks, @boazsender! I won't be able to log in to the VM until this change is applied. Would you mind running Ansible from `master`?

**Comment by boazsender** [comment]
@jugglinmike I just ran the add users command from master. Are you in? Sorry for the delay!

**Comment by jugglinmike** [comment]
I am indeed! No worries about the delay; I've been busy, too

**Pull request merged**
