### PR TITLE
add all jobs to job list

### PR DESCRIPTION
**Pull request by bobholt**
This adds all build jobs to the list in the app - not just browser jobs and corrects an issue where failing jobs were reporting "STARTED" status.

It looks like this: https://pulls-staging.web-platform-tests.org/build/339

Will address adding list of failing non-browser jobs to GitHub comments in a separate PR.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wptdash/14)

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wptdash/blueprints/routes.py, line 512 at r1](https://reviewable.io:443/reviews/w3c/wptdash/14#-Kr7nrE2punI8KfHpTcp:-Kr7nrE2punI8KfHpTcq:bpt07mq) ([raw file](https://github.com/w3c/wptdash/blob/07925290847fa13e308aea5462a062113fc558e9/wptdash/blueprints/routes.py#L512)):*
> ```Python
> 
> def add_job_to_session(job_data, build, db, models):
>     job_env = next(
> ```

Seems like there's a log of repetition here. Can we have a loop or a function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptdash/14)*

**Comment by bobholt** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[wptdash/blueprints/routes.py, line 512 at r1](https://reviewable.io:443/reviews/w3c/wptdash/14#-Kr7nrE2punI8KfHpTcp:-KrBlD3uddTiyz1lTaKP:b-av9kt) ([raw file](https://github.com/w3c/wptdash/blob/07925290847fa13e308aea5462a062113fc558e9/wptdash/blueprints/routes.py#L512)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Seems like there's a log of repetition here. Can we have a loop or a function?
</blockquote></details>

Moved to a function (`dictify_env_list`) that allows us to do a simple lookup in this function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptdash/14)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wptdash/blueprints/routes.py, line 512 at r2](https://reviewable.io:443/reviews/w3c/wptdash/14#-KrFZddoH7JUKCp4iDga:-KrFZddpi4oO1uKZQ3kb:b-t54kyg) ([raw file](https://github.com/w3c/wptdash/blob/3bd57d1206c206b88e3f3c9bc734cf7fdf83ca56/wptdash/blueprints/routes.py#L512)):*
> ```Python
>     env_dict = {}
>     for env_string in env_list:
>         env_vars = env_string.split(' ')
> ```

Try `import shlex; shlex.split(env_string)`.  I think that will simplify things here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptdash/14)*

**Comment by jgraham** [comment]
Reviewed 1 of 3 files at r3.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wptdash/14)*

**Review by jgraham — APPROVED** [review]

**Pull request merged**
