### PR TITLE
Ignore .DS_Store files (Mac Finder)

### PR DESCRIPTION
**Pull request by lukebjerring**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-pullresults/36)

### CODE REVIEW

**Comment by gsnedders** [comment]
FWIW, I'd strongly recommend all macOS users putting https://github.com/github/gitignore/blob/master/Global/macOS.gitignore at $HOME/.config/git/ignore to ignore macOS files globally.

**Comment by bobholt** [comment]
I agree with @gsnedders and almost said as much on @AutomatedTester's [PR in wptdashboard](https://github.com/w3c/wptdashboard/pull/150).

That said, I'm fine adding it to the local gitignore because on a broad public project like this, I don't expect all future contributors will have set up a global or that we'd want to tell each of them to do that every time this comes up.

**Comment by AutomatedTester** [comment]
While I agree, I feel this is a flaw in git that people have to manually handle this.

**Comment by gsnedders** [comment]
@bobholt Yeah, I've no strong objection to putting super-common things like `.DS_Store` in per-project `.gitignore` files, given we see such files get committed often enough.

**Pull request merged**
